version: '3.1'

services:
  mybit:
    build:
      dockerfile: ./Dockerfile.dev
      context: .     
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=production